# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZu0xce-voSZpxe-Kkj8DeYjH65Q3QNe
"""

!pip install cryptography

from cryptography.fernet import Fernet
#Generate a new Fernet key
key=Fernet.generate_key()
#create a Fernet instance using the generated key
fernet=Fernet(key)
message1="First Name"
message2="KEZA"
#Encrypt message1 using the Fernet instance
encrypted_message1=fernet.encrypt(message1.encode())#Encode message to bytes
#Decrpyt message2 using the Fernet instance
decrypted_message1=fernet.decrypt(encrypted_message1)
#Encrypt message2 using the Fernet instance
encrypted_message2 = fernet.encrypt(message2.encode())#Encode message to bytes
#Decrypt message2 using the Fernet instance
decrypted_message2=fernet.decrypt(encrypted_message2)
#Print the decrypted message
print (decrypted_message1.decode())#Decode back to string
#Print the decrypted message
print(decrypted_message2.decode())#Decode back to string